const productRows = [
    {
        id: 1,
        name: "Screen",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 134,
        status: "active",
        price: "$120",
    },
    {
        id: 2,
        name: "Labtop",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 140,
        status: "active",
        price: "$310",
    },
    {
        id: 3,
        name: "Phones",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 180,
        status: "active",
        price: "$170",
    },
    {
        id: 4,
        name: "Apple Airpods",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 133,
        status: "active",
        price: "$220",
    },
    {
        id: 5,
        name: "Chargers",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 145,
        status: "active",
        price: "$160",
    },
    {
        id: 6,
        name: "Sony Screens",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 124,
        status: "active",
        price: "$320",
    },
    {
        id: 7,
        name: "Samsung Chargers",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 123,
        status: "active",
        price: "$210",
    },
    {
        id: 8,
        name: "Mobiles",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 124,
        status: "active",
        price: "$150",
    },
    {
        id: 9,
        name: "Headphones",
        img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
        stock: 142,
        status: "active",
        price: "$220",
    },
];
export default productRows;
